variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}

variable "cluster_node_pool" {
  type = object({
    name                          = string
    kubernetes_cluster_id         = string
    vm_size                       = optional(string, "Standard_DS3_v2")
    capacity_reservation_group_id = optional(string)
    temporary_name_for_rotation   = optional(string, null)
    auto_scaling_enabled          = optional(bool, true)
    max_count                     = optional(number)
    min_count                     = optional(number)
    node_count                    = optional(number)
    host_encryption_enabled       = optional(bool, false)
    node_public_ip_enabled        = optional(bool, false)
    eviction_policy               = optional(string)
    host_group_id                 = optional(string)
    kubelet_config = optional(object({
      allowed_unsafe_sysctls    = optional(string)
      container_log_max_size_mb = optional(number)
      cpu_cfs_quota_enabled     = optional(bool)
      cpu_cfs_quota_period      = optional(number)
      cpu_manager_policy        = optional(string)
      image_gc_high_threshold   = optional(number)
      image_gc_low_threshold    = optional(number)
      pod_max_pid               = optional(number)
      topology_manager_policy   = optional(string)
    }))
    linux_os_config = optional(object({
      swap_file_size_mb = optional(number)
      sysctl_config = optional(object({
        fs_aio_max_nr                      = optional(number)
        fs_file_max                        = optional(number)
        fs_inotify_max_user_watches        = optional(number)
        fs_nr_open                         = optional(number)
        kernel_threads_max                 = optional(number)
        net_core_netdev_max_backlog        = optional(number)
        net_core_optmem_max                = optional(number)
        net_core_rmem_default              = optional(number)
        net_core_rmem_max                  = optional(number)
        net_core_somaxconn                 = optional(number)
        net_core_wmem_default              = optional(number)
        net_core_wmem_max                  = optional(number)
        net_ipv4_ip_local_port_range_max   = optional(number)
        net_ipv4_ip_local_port_range_min   = optional(number)
        net_ipv4_neigh_default_gc_thresh1  = optional(number)
        net_ipv4_neigh_default_gc_thresh2  = optional(number)
        net_ipv4_neigh_default_gc_thresh3  = optional(number)
        net_ipv4_tcp_fin_timeout           = optional(number)
        net_ipv4_tcp_keepalive_intvl       = optional(number)
        net_ipv4_tcp_keepalive_probes      = optional(number)
        net_ipv4_tcp_keepalive_time        = optional(number)
        net_ipv4_tcp_max_syn_backlog       = optional(number)
        net_ipv4_tcp_max_tw_buckets        = optional(number)
        net_ipv4_tcp_tw_reuse              = optional(bool)
        net_netfilter_nf_conntrack_buckets = optional(number)
        net_netfilter_nf_conntrack_max     = optional(number)
        vm_max_map_count                   = optional(number)
        vm_swappiness                      = optional(number)
        vm_vfs_cache_pressure              = optional(number)
      }))
      transparent_huge_page_defrag  = optional(string)
      transparent_huge_page_enabled = optional(string)
    }))
    fips_enabled      = optional(bool, false)
    gpu_instance      = optional(string)
    kubelet_disk_type = optional(string)
    max_pods          = optional(number, 30)
    mode              = optional(string, "User")
    node_network_profile = optional(object({
      allowed_host_ports = optional(list(object({
        port_start = optional(number)
        port_end   = optional(number)
        protocol   = optional(string)
      })))
      application_security_group_ids = optional(list(string))
      node_public_ip_tags            = optional(map(string))
    }))
    node_labels                  = optional(map(string))
    node_taints                  = optional(list(string))
    orchestrator_version         = optional(string)
    os_disk_size_gb              = optional(number, 120)
    os_disk_type                 = optional(string, "Ephemeral")
    pod_subnet_id                = optional(string)
    os_sku                       = optional(string, "AzureLinux")
    os_type                      = optional(string, "Linux")
    priority                     = optional(string, "Regular")
    proximity_placement_group_id = optional(string)
    spot_max_price               = optional(number)
    snapshot_id                  = optional(string)
    tags                         = optional(map(string), {})
    scale_down_mode              = optional(string, "Delete")
    ultra_ssd_enabled            = optional(bool, false)
    upgrade_settings = optional(object({
      drain_timeout_in_minutes      = optional(number)
      node_soak_duration_in_minutes = optional(number, 0)
      max_surge                     = optional(string, "33%")
    }))
    vnet_subnet_id = string
    windows_profile = optional(object({
      outbound_nat_enabled = optional(bool)
    }))
    workload_runtime = optional(string)
    zones            = optional(list(number), [1, 2, 3])
  })
}